import { getServerUser } from "@/lib/auth/serverUser";
import Link from "next/link";

export default async function AdminPage() {
  const user = await getServerUser();

  return (
    <main className="container">
      <div className="card">
        <h1 className="h1">Admin Panel</h1>
        <p className="p">
          This page is protected by middleware (requires login). Admin-only APIs are protected by simulated role checks.
        </p>
        <hr className="sep" />
        <p className="p">Logged in as: <span className="mono">{user?.email ?? "unknown"}</span></p>
        <div className="row" style={{ marginTop: 12 }}>
          <Link className="btn" href="/labs">Back to Labs</Link>
          <Link className="btn primary" href="/labs/authorization">Authorization Lab</Link>
        </div>
      </div>

      <div className="card" style={{ marginTop: 16 }}>
        <div className="h2">Audit Logs</div>
        <p className="p">If you create the <span className="mono">audit_logs</span> table in Supabase, you can fetch and show logs here later.</p>
        <div className="code" style={{ marginTop: 12 }}>
{`-- Supabase SQL:
create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid,
  email text,
  action text not null,
  ok boolean not null,
  reason text,
  created_at timestamp with time zone default now()
);`}
        </div>
      </div>
    </main>
  );
}
