import { supabaseServer } from "@/lib/supabase/server";
import { getServerUser } from "@/lib/auth/serverUser";

/**
 * Writes audit logs to Supabase (optional).
 * If the audit_logs table does not exist, this function fails silently.
 *
 * Supabase table:
 *
 * create table audit_logs (
 *   id bigint generated by default as identity primary key,
 *   user_id uuid,
 *   email text,
 *   action text not null,
 *   ok boolean not null,
 *   reason text,
 *   created_at timestamp with time zone default now()
 * );
 */
export async function audit(
  action: string,
  ok: boolean,
  reason?: string
) {
  try {
    const user = await getServerUser();

    const supabase = await supabaseServer();

    await supabase.from("audit_logs").insert({
      user_id: user?.id ?? null,
      email: user?.email ?? null,
      action,
      ok,
      reason: reason ?? null,
    });
  } catch {
    // Silent failure by design:
    // - Educational project
    // - Logging must never break the app
  }
}
